basePath: /v1
definitions:
  server.ArticleResponse:
    properties:
      article:
        $ref: '#/definitions/service.Article'
    type: object
  server.CreateFeed:
    properties:
      name:
        example: My Feed
        type: string
      url:
        example: https://example.com/feed.xml
        type: string
    required:
    - url
    type: object
  server.CreateFeedRequest:
    properties:
      feed:
        $ref: '#/definitions/server.CreateFeed'
    type: object
  server.CreateResponse:
    properties:
      id:
        type: string
    type: object
  server.ErrorResponse:
    properties:
      error:
        example: unable to fetch feeds
        type: string
    type: object
  server.FeedArticlesResponse:
    properties:
      articles:
        items:
          $ref: '#/definitions/service.Article'
        type: array
    type: object
  server.FeedResponse:
    properties:
      feed:
        $ref: '#/definitions/service.Feed'
    type: object
  server.FeedsResponse:
    properties:
      feeds:
        items:
          $ref: '#/definitions/server.ListFeed'
        type: array
    type: object
  server.ListFeed:
    properties:
      id:
        example: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
        type: string
      name:
        example: Example
        type: string
      url:
        example: https://example.com/
        type: string
    type: object
  server.UpdateFeed:
    properties:
      name:
        example: My Feed
        type: string
      url:
        example: https://example.com/feed.xml
        type: string
    required:
    - url
    type: object
  server.UpdateFeedRequest:
    properties:
      feed:
        $ref: '#/definitions/server.UpdateFeed'
    type: object
  server.UpdateResponse:
    properties:
      id:
        type: string
    type: object
  service.Article:
    properties:
      authorEmail:
        type: string
      authorName:
        type: string
      content:
        type: string
      feedId:
        type: string
      guid:
        type: string
      id:
        type: string
      imageUrl:
        type: string
      preview:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  service.Feed:
    properties:
      id:
        type: string
      name:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Feed API
  version: "1.0"
paths:
  /articles/{id}:
    get:
      consumes:
      - application/json
      description: view article
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.ArticleResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: view article
  /feeds:
    get:
      consumes:
      - application/json
      description: list feeds
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedsResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: list feeds
    post:
      consumes:
      - application/json
      description: create feed
      parameters:
      - description: feed data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.CreateFeedRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.CreateResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: create feed
  /feeds/{id}:
    get:
      consumes:
      - application/json
      description: view feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: view feed
    put:
      consumes:
      - application/json
      description: update feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: string
      - description: feed data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.UpdateFeedRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.UpdateResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: update feed
  /feeds/{id}/articles:
    get:
      consumes:
      - application/json
      description: list articles for a feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedArticlesResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: list articles for a feed
swagger: "2.0"
