basePath: /v1
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Article:
    properties:
      authorEmail:
        example: example@example.com
        type: string
      authorName:
        example: Eric Butera
        type: string
      content:
        example: Article content text. May contain HTML.
        type: string
      createdAt:
        example: "2021-01-01T00:00:00Z"
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      feed:
        $ref: '#/definitions/models.Feed'
      feedId:
        example: 1
        type: integer
      guid:
        example: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
        type: string
      id:
        example: 1
        type: integer
      imageUrl:
        example: https://example.com/image.jpg
        type: string
      preview:
        example: Article preview text. May contain HTML.
        type: string
      title:
        example: Example Article
        type: string
      updatedAt:
        example: "2021-01-01T00:00:00Z"
        type: string
      url:
        example: https://example.com/
        type: string
    required:
    - feedId
    - id
    - url
    type: object
  models.Feed:
    properties:
      createdAt:
        example: "2021-01-01T00:00:00Z"
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        example: 1
        type: integer
      name:
        example: Example
        type: string
      updatedAt:
        example: "2021-01-01T00:00:00Z"
        type: string
      url:
        example: https://example.com/
        type: string
    required:
    - id
    - url
    type: object
  server.ArticleResponse:
    properties:
      article:
        $ref: '#/definitions/models.Article'
    type: object
  server.CreateFeed:
    properties:
      name:
        example: My Feed
        type: string
      url:
        example: https://example.com/feed.xml
        type: string
    required:
    - url
    type: object
  server.CreateFeedRequest:
    properties:
      feed:
        $ref: '#/definitions/server.CreateFeed'
    type: object
  server.ErrorResponse:
    properties:
      error:
        example: unable to fetch feeds
        type: string
    type: object
  server.FeedArticlesResponse:
    properties:
      articles:
        items:
          $ref: '#/definitions/models.Article'
        type: array
    type: object
  server.FeedCreateResponse:
    properties:
      feed:
        allOf:
        - $ref: '#/definitions/models.Feed'
        description: 'TODO: limit fields'
    type: object
  server.FeedResponse:
    properties:
      feed:
        $ref: '#/definitions/models.Feed'
    type: object
  server.FeedUpdateResponse:
    properties:
      feed:
        $ref: '#/definitions/models.Feed'
    type: object
  server.FeedsResponse:
    properties:
      feeds:
        items:
          $ref: '#/definitions/models.Feed'
        type: array
    type: object
  server.UpdateFeed:
    properties:
      name:
        example: My Feed
        type: string
      url:
        example: https://example.com/feed.xml
        type: string
    required:
    - url
    type: object
  server.UpdateFeedRequest:
    properties:
      feed:
        $ref: '#/definitions/server.UpdateFeed'
    type: object
host: localhost:8080
info:
  contact: {}
  title: Feed API
  version: "1.0"
paths:
  /articles/{id}:
    get:
      consumes:
      - application/json
      description: view article
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.ArticleResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: view article
  /feeds:
    get:
      consumes:
      - application/json
      description: list feeds
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedsResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: list feeds
    post:
      consumes:
      - application/json
      description: create feed
      parameters:
      - description: feed data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.CreateFeedRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedCreateResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: create feed
  /feeds/{id}:
    get:
      consumes:
      - application/json
      description: view feed
      parameters:
      - description: Feed ID
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: view feed
    put:
      consumes:
      - application/json
      description: update feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      - description: feed data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.UpdateFeedRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedUpdateResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: update feed
  /feeds/{id}/articles:
    get:
      consumes:
      - application/json
      description: list articles for a feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.FeedArticlesResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: list articles for a feed
swagger: "2.0"
