load("ext://helm_resource", "helm_resource", "helm_repo")
load('ext://secret', 'secret_create_generic', 'secret_from_dict')

# Minio object storage
def deploy_minio(
    secret_name="feed-minio-auth",
    auto_init=True,
):
    k8s_resource(
        "minio",
        port_forwards=[
            port_forward(9100, 9000, "minio-service"),
            port_forward(9101, 9001, "minio-admin"),
        ],
        auto_init=auto_init,
        labels=["services"],
    )