load("ext://helm_resource", "helm_resource", "helm_repo")
load('ext://secret', 'secret_create_generic', 'secret_from_dict')

# Minio object storage
# https://github.com/bitnami/charts/tree/main/bitnami/minio
def deploy_minio(
    secret_name="feed-minio-auth",
    root_user="minio",
    root_password="minio-password",
    helm_repo_name="bitnami",
    helm_repo_url="https://charts.bitnami.com/bitnami",
    chart_name="bitnami/minio",
    chart_flags=None,
    port_mappings=None,
    labels=None,
    auto_init=True,
):
    if not chart_flags:
        chart_flags = [
            "--set=auth.existingSecret="+ secret_name,
            '--set=defaultBuckets="icons;feeds"',
            "--set=service.type=LoadBalancer",
            "--set=mode=standalone",
            "--set=persistence.enabled=false",
            "--set=replicas=1",
            "--set=consoleService.type=LoadBalancer",
            "--set=resources.requests.memory=256Mi",
        ]

    if not port_mappings:
        port_mappings = [
            port_forward(9100, 9000, "minio-service"),
            port_forward(9101, 9001, "minio-admin"),
        ]

    if not labels:
        labels = ["data-pipeline"]

    k8s_yaml(
        secret_from_dict(
            secret_name,
            inputs={
                "root-user": root_user,
                "root-password": root_password,
            },
        )
    )

    # TODO: revisit- i was getting an error saying repo doesn't exist:
    # Running cmd: helm repo add bitnami https://charts.bitnami.com/bitnami --force-update
    # Release "minio" does not exist. Installing it now.
    # Error: repo bitnami not found
    local('helm repo add bitnami https://charts.bitnami.com/bitnami --force-update')
    local('helm repo update')

    helm_repo(helm_repo_name, helm_repo_url)
    helm_resource(
        name="minio",
        chart="bitnami/minio",
        flags=chart_flags,
        port_forwards=port_mappings,
        auto_init=auto_init,
        labels=labels,
    )
