// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddFeedResponse struct {
	ID string `json:"id"`
}

type Article struct {
	ID          string  `json:"id"`
	FeedID      string  `json:"feedId"`
	URL         string  `json:"url"`
	Title       string  `json:"title"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	Content     string  `json:"content"`
	Preview     string  `json:"preview"`
	GUID        *string `json:"guid,omitempty"`
	AuthorName  *string `json:"authorName,omitempty"`
	AuthorEmail *string `json:"authorEmail,omitempty"`
}

type Feed struct {
	ID   string `json:"id"`
	URL  string `json:"url"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateFeedResponse struct {
	ID string `json:"id"`
}
