# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - exportloopref
    - godot
    - godox
    - exhaustruct
    - depguard
    - gochecknoinits
    - nlreturn
    - gomoddirectives
    - wsl
    - wrapcheck
    - nonamedreturns
    - paralleltest
    - varnamelen
    - ireturn
    - tagliatelle
    - forbidigo
    - gochecknoglobals
    - inamedparam
    - interfacebloat
    - perfsprint
    - nilnil
    - stylecheck
    - thelper
    - forcetypeassert
    - mnd
    - intrange
    - lll
    - gocritic

linters-settings:
  tagalign:
    align: true
    sort: false
    strict: false
  # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: flag-parameter
        exclude:
          - "rpc/pkg/client/client.go"
      - name: import-shadowing
        disabled: true
      - name: import-alias-naming
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: unchecked-type-assertion
        exclude:
          - '_test\\.go$'
      - name: unused-receiver
        exclude:
          - graph/extensions/prometheus/prometheus.go
      - name: max-public-structs
        disabled: true
      # - name: var-naming
      #   severity: warning
      #   disabled: false
      #   exclude:
      #     - \\root\\.go$
      #   arguments:
      #     - ["ID", "RPC", "URL", "GUID", "HTML"] # AllowList
      #     - ["VM"] # DenyList
      #     - - upperCaseConst: true # Extra parameter (upperCaseConst|skipPackageNameChecks)

      # TODO: temporary disabled
      - name: var-naming
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: cognitive-complexity
        disabled: true

# https://golangci-lint.run/usage/configuration/#issues-configuration
issues:
  exclude-rules:
    - path: api/
      linters:
        - depguard
        - revive
    - path: cli/
      linters:
        - revive
    - path: graph/graph/schema.resolvers_test.go
      linters:
        - revive
  exclude-files:
    - ".*\\.pb\\.go$"
    - pkg/feeds/v1/service_grpc.pb.go
    - internal/copygen/generated.go
    - graph/extensions/prometheus/prometheus.go
  whole-files: true
  fix: true
