with-expecter: true
inpackage: True

filename: "mock_{{.InterfaceName | lower }}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"

packages:
  github.com/ericbutera/amalgam/data-pipeline/temporal/feed/internal/transforms:
    interfaces:
      Transforms:
  github.com/ericbutera/amalgam/data-pipeline/temporal/internal/bucket:
    interfaces:
      Bucket:
  github.com/ericbutera/amalgam/data-pipeline/temporal/internal/feeds:
    interfaces:
      Feeds:
  github.com/ericbutera/amalgam/internal/http/fetch:
    interfaces:
      Fetch:
  github.com/ericbutera/amalgam/pkg/feeds/v1:
    config:
    interfaces:
      FeedServiceClient:
  github.com/ericbutera/amalgam/services/rpc/internal/tasks:
    interfaces:
      Tasks:
