repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: local
    hooks:
      # - id: local-lint
      #   name: local lint
      #   entry: make lint
      #   description: run project linters
      #   language: system
      #   pass_filenames: false
      #   stages: [pre-commit]
      - id: go-test
        name: go-test
        entry: make go-test
        description: golang tests
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: go-lint
        name: go-lint
        entry: make go-lint
        description: go linters
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: ts-test
        name: ts-test
        entry: make ts-test
        description: typescript tests
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: ts-lint
        name: ts-lint
        entry: make ts-lint
        description: typescript linters
        language: system
        pass_filenames: false
        stages: [pre-commit]
