-   id: lint
    name: lint
    entry: make lint
    description: run project linters
    language: script
-   id: test
    name: test
    entry: make test
    description: runs project unit tests
    language: script
