apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api-image
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GRAPH_HOST
              value: "http://graph:8080/query"
            - name: GIN_MODE
              value: "debug"
            - name: OTEL_ENABLE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "app"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://lgtm:4318"
            - name: OTEL_OTLP_EXPORT_INTERVAL
              value: "5000"
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "http://lgtm:4318/v1/metrics"
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "http://lgtm:4318/v1/logs"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=api,service.instance.id=api:8080"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: CORS_ALLOW_ORIGINS
              value: "http://localhost:3000"
            - name: CORS_ALLOW_METHODS
              value: "GET,POST,PUT,PATCH"
            - name: CORS_ALLOW_HEADERS
              value: "Content-Type,Authorization,Origin"
            - name: CORS_EXPOSE_HEADERS
              value: "Content-Length"
