apiVersion: v1
kind: Service
metadata:
  name: graph
spec:
  selector:
    app: graph
  ports:
    - name: graph
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph
  labels:
    app: graph
spec:
  selector:
    matchLabels:
      app: graph
  template:
    metadata:
      labels:
        app: graph
    spec:
      containers:
        - name: graph
          image: graph-image
          ports:
            - containerPort: 8080
          env:
            - name: API_HOST
              value: "api:8080"
            - name: API_SCHEME
              value: "http"
            - name: RPC_HOST
              value: "rpc:50051"
            - name: RPC_INSECURE
              value: "true"
            - name: OTEL_ENABLE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "graph"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://lgtm:4318"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
