apiVersion: batch/v1
kind: Job
metadata:
  name: k6
spec:
  template:
    spec:
      containers:
        - name: k6
          image: k6-image
          env:
            - name: K6_OUT
              value: json
            - name: API_HOST
              value: http://api:8080
            - name: GRAPH_HOST
              value: http://graph:8080/query
      restartPolicy: Never
  backoffLimit: 4
