apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql
  name: mysql
spec:
  ports:
    - name: mysql-server
      port: 3306
      targetPort: 3306
  selector:
    service: mysql
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          volumeMounts:
            - name: mysql-setup
              mountPath: /docker-entrypoint-initdb.d/setup.sql
              subPath: setup.sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          resources: {}
          # livenessProbe:
          #   exec:
          #     command: ["mysqladmin", "ping"]
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
      initContainers:
        - name: init-mysql-setup
          image: alpine:latest
          command:
            [
              "sh",
              "-c",
              "apk add --no-cache gettext && envsubst < /template/setup.sql > /config/setup.sql",
            ]
          env:
            - name: AMALGAM_MIGRATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: feed-mysql-auth
                  key: AMALGAM_MIGRATION_PASSWORD
            - name: AMALGAM_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: feed-mysql-auth
                  key: AMALGAM_USER_PASSWORD
          volumeMounts:
            - name: template
              mountPath: /template
            - name: mysql-setup
              mountPath: /config
      volumes:
        - name: template
          configMap:
            name: mysql-setup-sql
        - name: mysql-setup
          emptyDir: {}

      restartPolicy: Always
status: {}
--- # configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-setup-sql
data:
  # TODO: secrets manager
  setup.sql: |
    SET GLOBAL max_allowed_packet=32505856;
    CREATE DATABASE `amalgam-db`;

    CREATE USER 'amalgam-migration'@'%' IDENTIFIED WITH caching_sha2_password BY '${AMALGAM_MIGRATION_PASSWORD}';
    GRANT ALL PRIVILEGES ON `amalgam-db`.* TO 'amalgam-migration'@'%';

    CREATE USER 'amalgam-user'@'%' IDENTIFIED WITH caching_sha2_password BY '${AMALGAM_USER_PASSWORD}';
    GRANT SELECT, INSERT, UPDATE, DELETE ON `amalgam-db`.* TO 'amalgam-user'@'%';

    FLUSH PRIVILEGES;
