apiVersion: v1
kind: Service
metadata:
  name: rpc
spec:
  selector:
    app: rpc
  ports:
    - name: rpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc
  labels:
    app: rpc
spec:
  selector:
    matchLabels:
      app: rpc
  template:
    metadata:
      labels:
        app: rpc
    spec:
      containers:
        - name: rpc
          image: rpc-image
          ports:
            - containerPort: 50051
            - containerPort: 9090
          env:
            - name: PORT
              value: "50051"
            - name: OTEL_ENABLE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "rpc"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://lgtm:4318"
            - name: DB_ADAPTER
              value: "mysql"
            - name: DB_MYSQL_DSN
              valueFrom:
                secretKeyRef:
                  name: rpc-auth
                  key: DB_MYSQL_DSN
            # data pipeline tasks
            - name: TEMPORAL_HOST
              value: "temporal:7233"
            - name: GRAPHQL_HOST
              value: "graphql:8080"
            - name: FAKE_HOST
              value: "fake:8080"
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 5 # todo: configurable via values.yaml
