apiVersion: v1
kind: Service
metadata:
  name: sws
spec:
  selector:
    name: sws
  ports:
    - name: sws
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws
  labels:
    app: sws
spec:
  selector:
    matchLabels:
      app: sws
  template:
    metadata:
      labels:
        app: sws
    spec:
      containers:
        - name: sws
          image: sws-image
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_HOST
              value: "::"
            - name: SERVER_ROOT
              value: "/www"
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_LOG_LEVEL
              value: debug
            - name: SERVER_DIRECTORY_LISTING
              value: "true"
