/*
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.10.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = __ENV.API_HOST || "http://api:8080/v1";

console.log(`BASE_URL ${BASE_URL}`);

// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

const FEED_ID = "0e597e90-ece5-463e-8608-ff687bf286da";
const FEED_ID_UPDATE = "1e597e90-ece5-463e-8608-ff687bf286da";
const ARTICLE_ID = "2a1a227d-0375-4d9a-943f-85017ac4f930";

export default function () {
    group("/feeds/{id}", () => {
        let id = FEED_ID; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/feeds/${id}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2:
        // TODO: this test fails because rest api isn't handling updates correctly (currently trying to set created_at=null)
        {
            let url = BASE_URL + `/feeds/${FEED_ID_UPDATE}`;
            let body = { "feed": { "url": "https://example.com/k6" } };
            let params = {
                headers: {
                    "Content-Type": "application/json", "Accept": "application/json"
                }
            };
            let request = http.put(url, JSON.stringify(body), params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/feeds", () => {

        // Request No. 1:
        {
            let url = BASE_URL + `/feeds`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2:
        {
            let url = BASE_URL + `/feeds`;
            let body = { "feed": { "url": "https://example.com/k6" } };
            let params = {
                headers: {
                    "Content-Type": "application/json", "Accept": "application/json"
                }
            };
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/articles/{id}", () => {
        let id = ARTICLE_ID; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/articles/${id}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/feeds/{id}/articles", () => {
        let id = FEED_ID; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/feeds/${id}/articles`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

}
