/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GormDeletedAt
 */
export interface GormDeletedAt {
    /**
     * 
     * @type {string}
     * @memberof GormDeletedAt
     */
    time?: string;
    /**
     * Valid is true if Time is not NULL
     * @type {boolean}
     * @memberof GormDeletedAt
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the GormDeletedAt interface.
 */
export function instanceOfGormDeletedAt(value: object): value is GormDeletedAt {
    return true;
}

export function GormDeletedAtFromJSON(json: any): GormDeletedAt {
    return GormDeletedAtFromJSONTyped(json, false);
}

export function GormDeletedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): GormDeletedAt {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : json['time'],
        'valid': json['valid'] == null ? undefined : json['valid'],
    };
}

  export function GormDeletedAtToJSON(json: any): GormDeletedAt {
      return GormDeletedAtToJSONTyped(json, false);
  }

  export function GormDeletedAtToJSONTyped(value?: GormDeletedAt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'valid': value['valid'],
    };
}

