/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
    GormDeletedAtToJSONTyped,
} from './GormDeletedAt';

/**
 * 
 * @export
 * @interface ModelsFeed
 */
export interface ModelsFeed {
    /**
     * 
     * @type {string}
     * @memberof ModelsFeed
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsFeed
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof ModelsFeed
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsFeed
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFeed
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsFeed
     */
    url?: string;
}

/**
 * Check if a given object implements the ModelsFeed interface.
 */
export function instanceOfModelsFeed(value: object): value is ModelsFeed {
    return true;
}

export function ModelsFeedFromJSON(json: any): ModelsFeed {
    return ModelsFeedFromJSONTyped(json, false);
}

export function ModelsFeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsFeed {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'deletedAt': json['deletedAt'] == null ? undefined : GormDeletedAtFromJSON(json['deletedAt']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

  export function ModelsFeedToJSON(json: any): ModelsFeed {
      return ModelsFeedToJSONTyped(json, false);
  }

  export function ModelsFeedToJSONTyped(value?: ModelsFeed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'deletedAt': GormDeletedAtToJSON(value['deletedAt']),
        'id': value['id'],
        'name': value['name'],
        'updatedAt': value['updatedAt'],
        'url': value['url'],
    };
}

