/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsFeed } from './ModelsFeed';
import {
    ModelsFeedFromJSON,
    ModelsFeedFromJSONTyped,
    ModelsFeedToJSON,
    ModelsFeedToJSONTyped,
} from './ModelsFeed';

/**
 * 
 * @export
 * @interface ServerFeedResponse
 */
export interface ServerFeedResponse {
    /**
     * 
     * @type {ModelsFeed}
     * @memberof ServerFeedResponse
     */
    feed?: ModelsFeed;
}

/**
 * Check if a given object implements the ServerFeedResponse interface.
 */
export function instanceOfServerFeedResponse(value: object): value is ServerFeedResponse {
    return true;
}

export function ServerFeedResponseFromJSON(json: any): ServerFeedResponse {
    return ServerFeedResponseFromJSONTyped(json, false);
}

export function ServerFeedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerFeedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'feed': json['feed'] == null ? undefined : ModelsFeedFromJSON(json['feed']),
    };
}

  export function ServerFeedResponseToJSON(json: any): ServerFeedResponse {
      return ServerFeedResponseToJSONTyped(json, false);
  }

  export function ServerFeedResponseToJSONTyped(value?: ServerFeedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feed': ModelsFeedToJSON(value['feed']),
    };
}

