/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsArticle } from './ModelsArticle';
import {
    ModelsArticleFromJSON,
    ModelsArticleFromJSONTyped,
    ModelsArticleToJSON,
    ModelsArticleToJSONTyped,
} from './ModelsArticle';

/**
 * 
 * @export
 * @interface ServerArticleResponse
 */
export interface ServerArticleResponse {
    /**
     * 
     * @type {ModelsArticle}
     * @memberof ServerArticleResponse
     */
    article?: ModelsArticle;
}

/**
 * Check if a given object implements the ServerArticleResponse interface.
 */
export function instanceOfServerArticleResponse(value: object): value is ServerArticleResponse {
    return true;
}

export function ServerArticleResponseFromJSON(json: any): ServerArticleResponse {
    return ServerArticleResponseFromJSONTyped(json, false);
}

export function ServerArticleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerArticleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'article': json['article'] == null ? undefined : ModelsArticleFromJSON(json['article']),
    };
}

  export function ServerArticleResponseToJSON(json: any): ServerArticleResponse {
      return ServerArticleResponseToJSONTyped(json, false);
  }

  export function ServerArticleResponseToJSONTyped(value?: ServerArticleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': ModelsArticleToJSON(value['article']),
    };
}

