/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsFeed } from './ModelsFeed';
import {
    ModelsFeedFromJSON,
    ModelsFeedFromJSONTyped,
    ModelsFeedToJSON,
    ModelsFeedToJSONTyped,
} from './ModelsFeed';

/**
 * 
 * @export
 * @interface ServerFeedsResponse
 */
export interface ServerFeedsResponse {
    /**
     * 
     * @type {Array<ModelsFeed>}
     * @memberof ServerFeedsResponse
     */
    feeds?: Array<ModelsFeed>;
}

/**
 * Check if a given object implements the ServerFeedsResponse interface.
 */
export function instanceOfServerFeedsResponse(value: object): value is ServerFeedsResponse {
    return true;
}

export function ServerFeedsResponseFromJSON(json: any): ServerFeedsResponse {
    return ServerFeedsResponseFromJSONTyped(json, false);
}

export function ServerFeedsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerFeedsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'feeds': json['feeds'] == null ? undefined : ((json['feeds'] as Array<any>).map(ModelsFeedFromJSON)),
    };
}

  export function ServerFeedsResponseToJSON(json: any): ServerFeedsResponse {
      return ServerFeedsResponseToJSONTyped(json, false);
  }

  export function ServerFeedsResponseToJSONTyped(value?: ServerFeedsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feeds': value['feeds'] == null ? undefined : ((value['feeds'] as Array<any>).map(ModelsFeedToJSON)),
    };
}

