/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceArticle } from './ServiceArticle';
import {
    ServiceArticleFromJSON,
    ServiceArticleFromJSONTyped,
    ServiceArticleToJSON,
    ServiceArticleToJSONTyped,
} from './ServiceArticle';

/**
 *
 * @export
 * @interface ServerFeedArticlesResponse
 */
export interface ServerFeedArticlesResponse {
    /**
     *
     * @type {Array<ServiceArticle>}
     * @memberof ServerFeedArticlesResponse
     */
    articles?: Array<ServiceArticle>;
}

/**
 * Check if a given object implements the ServerFeedArticlesResponse interface.
 */
export function instanceOfServerFeedArticlesResponse(value: object): value is ServerFeedArticlesResponse {
    return true;
}

export function ServerFeedArticlesResponseFromJSON(json: any): ServerFeedArticlesResponse {
    return ServerFeedArticlesResponseFromJSONTyped(json, false);
}

export function ServerFeedArticlesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerFeedArticlesResponse {
    if (json == null) {
        return json;
    }
    return {

        'articles': json['articles'] == null ? undefined : ((json['articles'] as Array<any>).map(ServiceArticleFromJSON)),
    };
}

  export function ServerFeedArticlesResponseToJSON(json: any): ServerFeedArticlesResponse {
      return ServerFeedArticlesResponseToJSONTyped(json, false);
  }

  export function ServerFeedArticlesResponseToJSONTyped(value?: ServerFeedArticlesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'articles': value['articles'] == null ? undefined : ((value['articles'] as Array<any>).map(ServiceArticleToJSON)),
    };
}
