/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerCreateFeed
 */
export interface ServerCreateFeed {
    /**
     * 
     * @type {string}
     * @memberof ServerCreateFeed
     */
    url: string;
}

/**
 * Check if a given object implements the ServerCreateFeed interface.
 */
export function instanceOfServerCreateFeed(value: object): value is ServerCreateFeed {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ServerCreateFeedFromJSON(json: any): ServerCreateFeed {
    return ServerCreateFeedFromJSONTyped(json, false);
}

export function ServerCreateFeedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerCreateFeed {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

  export function ServerCreateFeedToJSON(json: any): ServerCreateFeed {
      return ServerCreateFeedToJSONTyped(json, false);
  }

  export function ServerCreateFeedToJSONTyped(value?: ServerCreateFeed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

