/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsFeed } from './ModelsFeed';
import {
    ModelsFeedFromJSON,
    ModelsFeedFromJSONTyped,
    ModelsFeedToJSON,
    ModelsFeedToJSONTyped,
} from './ModelsFeed';

/**
 * 
 * @export
 * @interface ServerFeedUpdateResponse
 */
export interface ServerFeedUpdateResponse {
    /**
     * 
     * @type {ModelsFeed}
     * @memberof ServerFeedUpdateResponse
     */
    feed?: ModelsFeed;
}

/**
 * Check if a given object implements the ServerFeedUpdateResponse interface.
 */
export function instanceOfServerFeedUpdateResponse(value: object): value is ServerFeedUpdateResponse {
    return true;
}

export function ServerFeedUpdateResponseFromJSON(json: any): ServerFeedUpdateResponse {
    return ServerFeedUpdateResponseFromJSONTyped(json, false);
}

export function ServerFeedUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerFeedUpdateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'feed': json['feed'] == null ? undefined : ModelsFeedFromJSON(json['feed']),
    };
}

  export function ServerFeedUpdateResponseToJSON(json: any): ServerFeedUpdateResponse {
      return ServerFeedUpdateResponseToJSONTyped(json, false);
  }

  export function ServerFeedUpdateResponseToJSONTyped(value?: ServerFeedUpdateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feed': ModelsFeedToJSON(value['feed']),
    };
}

