/* tslint:disable */
/* eslint-disable */
/**
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerCreateFeed } from './ServerCreateFeed';
import {
    ServerCreateFeedFromJSON,
    ServerCreateFeedFromJSONTyped,
    ServerCreateFeedToJSON,
    ServerCreateFeedToJSONTyped,
} from './ServerCreateFeed';

/**
 * 
 * @export
 * @interface ServerCreateFeedRequest
 */
export interface ServerCreateFeedRequest {
    /**
     * 
     * @type {ServerCreateFeed}
     * @memberof ServerCreateFeedRequest
     */
    feed?: ServerCreateFeed;
}

/**
 * Check if a given object implements the ServerCreateFeedRequest interface.
 */
export function instanceOfServerCreateFeedRequest(value: object): value is ServerCreateFeedRequest {
    return true;
}

export function ServerCreateFeedRequestFromJSON(json: any): ServerCreateFeedRequest {
    return ServerCreateFeedRequestFromJSONTyped(json, false);
}

export function ServerCreateFeedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerCreateFeedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'feed': json['feed'] == null ? undefined : ServerCreateFeedFromJSON(json['feed']),
    };
}

  export function ServerCreateFeedRequestToJSON(json: any): ServerCreateFeedRequest {
      return ServerCreateFeedRequestToJSONTyped(json, false);
  }

  export function ServerCreateFeedRequestToJSONTyped(value?: ServerCreateFeedRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feed': ServerCreateFeedToJSON(value['feed']),
    };
}

