{
 "title": "graph service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests Started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "graphql_request_started_total", "legendFormat": "Total Requests Started" }
   ]
  },
  {
   "title": "Requests Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "graphql_request_completed_total",
     "legendFormat": "Total Requests Completed"
    }
   ]
  },
  {
   "title": "Resolvers Started by Object and Field",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "graphql_resolver_started_total", "legendFormat": "{{object}} - {{field}}" }
   ]
  },
  {
   "title": "Resolvers Completed by Object and Field",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "graphql_resolver_completed_total",
     "legendFormat": "{{object}} - {{field}}"
    }
   ]
  },
  {
   "title": "Time to Resolve Field",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "graphql_resolver_duration_ms_bucket",
     "legendFormat": "{{exitStatus}} - {{object}} - {{field}}"
    }
   ]
  },
  {
   "title": "Time to Handle Request",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "graphql_request_duration_ms_bucket",
     "legendFormat": "{{exitStatus}}"
    }
   ]
  }
 ]
}