storage:
  tsdb:
    # A 10min time window is enough because it can easily absorb retries and network delays.
    out_of_order_time_window: 10m

scrape_configs:
  - job_name: "api"
    scrape_interval: 30s
    static_configs:
      - targets: ["api:8080"]
  - job_name: "rpc"
    scrape_interval: 30s
    static_configs:
      - targets: ["rpc:9090"]
  - job_name: "graph"
    scrape_interval: 30s
    static_configs:
      - targets: ["graph:8080"]
  - job_name: "temporal"
    scrape_interval: 30s
    static_configs:
      - targets: ["temporal:9090"]
  - job_name: "feed-worker"
    scrape_interval: 30s
    static_configs:
      - targets: ["feed-worker:9090"]
