{
 "title": "ingestion dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "records created",
   "type": "stat",
   "description": "shows the number of records created",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpc_articles_created_total", "legendFormat": "articles" },
    { "expr": "rpc_feeds_created_total", "legendFormat": "feeds" }
   ]
  },
  {
   "title": "activity errors",
   "type": "stat",
   "description": "data pipeline failure counters",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temporal_activity_execution_failed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rpc endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"CreateFeed|SaveArticle\"}[5m])) by (grpc_method, le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95, sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"CreateFeed|SaveArticle\"}[5m])) by (grpc_method, le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.50, sum(rate(grpc_server_handling_seconds_bucket{grpc_method=~\"CreateFeed|SaveArticle\"}[5m])) by (grpc_method, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "workflow latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_workflow_task_execution_latency_seconds_bucket{job=\"feed-worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_seconds_bucket{job=\"feed-worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(temporal_workflow_task_execution_latency_seconds_bucket{job=\"feed-worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "temporal stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Success By Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (workflow_type) (rate(temporal_workflow_completed_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workflow Failures By Type",
     "type": "timeseries",
     "description": "Workflow failures will show here. Panel shows \"no data\" if everything works.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by (workflow_type) (rate(temporal_workflow_failed_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Activity Execution Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_seconds_bucket[5m])) by (activity_type, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workflow Completion",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(temporal_workflow_completed_total[$__rate_interval]))",
       "legendFormat": "completed"
      },
      {
       "expr": "sum(rate(temporal_workflow_failed_total[$__rate_interval]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(rate(temporal_workflow_canceled_total[$__rate_interval]))",
       "legendFormat": "canceleld"
      },
      {
       "expr": "sum(rate(temporal_workflow_continue_as_new_total[$__rate_interval]))",
       "legendFormat": "continue as new"
      }
     ]
    },
    {
     "title": "Workflow Task Throughput By WorkflowType",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by (workflow_type) (rate(temporal_workflow_task_queue_poll_succeed_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Activity End-To-End Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_succeed_endtoend_latency_seconds_bucket[5m])) by (activity_type, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Activity Throughput By Activity Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "sum by (activity_type) (rate(temporal_activity_execution_latency_seconds_bucket[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}