{
 "title": "amalgam logs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "rpc",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"rpc\"} | json"
    }
   ]
  },
  {
   "title": "graph",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"graph\"} | json"
    }
   ]
  },
  {
   "title": "feed worker",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"feed-worker\"} | json"
    }
   ]
  },
  {
   "title": "feed task worker",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"feed-tasks-worker\"} | json"
    }
   ]
  },
  {
   "title": "ui",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=\"ui\"} | json"
    }
   ]
  }
 ]
}