{
 "title": "temporal - sdk metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace" },
   { "name": "WorkflowType" }
  ]
 },
 "panels": [
  { "title": "RPC Overview ($Namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Vs Failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_request[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(temporal_request_failure[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "RPC Requests Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) ((rate(temporal_request{namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Failures Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(temporal_request_failure{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Latencies ($Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, operation, le) (rate(temporal_request_latency_bucket{namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ namespace }} - {{ operation }}"
    }
   ]
  },
  { "title": "Workflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Workflow Completion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_workflow_completed_total{}[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(temporal_workflow_failed_total{}[5m]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(temporal_workflow_canceled_total{}[5m]))",
     "legendFormat": "canceled"
    },
    {
     "expr": "sum(rate(temporal_workflow_continue_as_new_total{}[5m]))",
     "legendFormat": "continued_as_new"
    }
   ]
  },
  {
   "title": "Workflow End-To-End Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_endtoend_latency_seconds_bucket[$__rate_interval])) by (workflow_type, le))",
     "legendFormat": "{{ namespace }} - {{ workflow_type }}"
    }
   ]
  },
  {
   "title": "Workflow Success By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_completed_total[$__rate_interval]))",
     "legendFormat": "{{ namespace }} - {{ workflow_type }}"
    }
   ]
  },
  {
   "title": "Workflow Failures By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workflow_type) (rate(temporal_workflow_failed_total[$__rate_interval]))",
     "legendFormat": "{{ namespace }} - {{ workflow_type }}"
    }
   ]
  },
  { "title": "Workflow Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Workflow Task Throughput By WorkflowType",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workflow_type) (rate(temporal_workflow_task_queue_poll_succeed_total[$__rate_interval]))",
     "legendFormat": "{{ namespace }} - {{ workflow_type }}"
    }
   ]
  },
  {
   "title": "Workflow Task Throughput By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workflow_type) (rate(temporal_workflow_task_queue_poll_succeed_total[$__rate_interval]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Empty Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(temporal_workflow_task_queue_poll_empty{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "Empty Poll - {{ namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Task Backlog By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Task Backlog By Workflow Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
     "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
    }
   ]
  },
  {
   "title": "Workflow Task Failed By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (activity_type) (rate(temporal_activity_execution_failed_total[5m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Task Failed By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_task_execution_failed{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
    }
   ]
  },
  {
   "title": "Workflow Task Execution Latency By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Task Execution Latency By Workflow Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
     "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
    }
   ]
  },
  {
   "title": "Workflow Task Replay Latency By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Task Replay Latency By Workflow Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
     "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
    }
   ]
  },
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Activity Throughput By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(temporal_activity_execution_latency_count{namespace=~\"$Namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Activity Throughput By Activity Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (activity_type) (rate(temporal_activity_execution_latency_seconds_bucket[5m]))",
     "legendFormat": "{{ namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Failed Activity by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, activity_type) (rate(temporal_activity_execution_failed{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Activity Execution Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_seconds_bucket[5m])) by (activity_type, le))",
     "legendFormat": "{{ namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Activity End-To-End Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_succeed_endtoend_latency_seconds_bucket[5m])) by (activity_type, le))"
    }
   ]
  },
  { "title": "Activity Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Empty Activity Polls By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(temporal_activity_poll_no_task{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Activity Task Backlog By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))"
    }
   ]
  },
  {
   "title": "Activity Task Backlog By Activity Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, activity_type, le))",
     "legendFormat": "{{ namespace }} - {{ activity_type }}"
    }
   ]
  },
  {
   "title": "Sticky Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sticky Cache Hit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_hit{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Miss",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 6 },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_miss{namespace=~\"Namespace\"}[5m]))",
       "legendFormat": "{{ namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Forced Eviction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_total_forced_eviction{namespace=~\"Namespace\"}[5m]))",
       "legendFormat": "{{ namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by (namespace) (temporal_sticky_cache_size)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  }
 ]
}