# TODO: helm chart w/ values.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api-image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GIN_MODE
          value: "debug"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://lgtm:4318"
        - name: OTEL_OTLP_EXPORT_INTERVAL
          value: "5000"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: "http://lgtm:4318/v1/metrics"
        - name: OTEL_METRIC_EXPORT_INTERVAL
          value: "5000"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=api"