/*
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.10.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://api:8080"; // TODO: define base url
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function () {
    group("/health", () => {

        // Request No. 1:
        {
            let url = BASE_URL + `/health`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/article/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // TODO: specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/article/${id}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/feeds", () => {

        // Request No. 1:
        {
            let url = BASE_URL + `/feeds`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/feed/{id}/articles", () => {
        let id = 'TODO_EDIT_THE_ID'; // TODO: specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/feed/${id}/articles`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

}
