/*
 * Feed API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.10.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://api:8080/v1";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function () {
    group("/feeds/{id}", () => {
        let id = '1'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/feeds/${id}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2:
        {
            // TODO: this fails because there isn't post body yet
            let url = BASE_URL + `/feeds/${id}`;
            let request = http.post(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/feeds", () => {

        // Request No. 1:
        {
            let url = BASE_URL + `/feeds`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2:
        {
            let url = BASE_URL + `/feeds`;
            let request = http.post(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/articles/{id}", () => {
        let id = '1'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/articles/${id}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/feeds/{id}/articles", () => {
        let id = '1'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1:
        {
            let url = BASE_URL + `/feeds/${id}/articles`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

}
