// Code generated by mockery v2.47.0. DO NOT EDIT.

package tasks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTasks is an autogenerated mock type for the Tasks type
type MockTasks struct {
	mock.Mock
}

type MockTasks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTasks) EXPECT() *MockTasks_Expecter {
	return &MockTasks_Expecter{mock: &_m.Mock}
}

// Status provides a mock function with given fields: ctx, taskID
func (_m *MockTasks) Status(ctx context.Context, taskID string) (*TaskStatusResult, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *TaskStatusResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*TaskStatusResult, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *TaskStatusResult); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TaskStatusResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTasks_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockTasks_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockTasks_Expecter) Status(ctx interface{}, taskID interface{}) *MockTasks_Status_Call {
	return &MockTasks_Status_Call{Call: _e.mock.On("Status", ctx, taskID)}
}

func (_c *MockTasks_Status_Call) Run(run func(ctx context.Context, taskID string)) *MockTasks_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTasks_Status_Call) Return(_a0 *TaskStatusResult, _a1 error) *MockTasks_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTasks_Status_Call) RunAndReturn(run func(context.Context, string) (*TaskStatusResult, error)) *MockTasks_Status_Call {
	_c.Call.Return(run)
	return _c
}

// GetResult provides a mock function with given fields: ctx, taskID
func (_m *MockTasks) GetResult(ctx context.Context, taskID string) (*TaskWorkflowResult, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetResult")
	}

	var r0 *TaskWorkflowResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*TaskWorkflowResult, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *TaskWorkflowResult); ok {
		r0 = rf(ctx, taskID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*TaskWorkflowResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MockTasks_GetResult_Call struct {
	*mock.Call
}

func (_e *MockTasks_Expecter) GetResult(ctx interface{}, taskID interface{}) *MockTasks_GetResult_Call {
	return &MockTasks_GetResult_Call{Call: _e.mock.On("GetResult", ctx, taskID)}
}

func (_c *MockTasks_GetResult_Call) Run(run func(ctx context.Context, taskID string)) *MockTasks_GetResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTasks_GetResult_Call) Return(_a0 *TaskWorkflowResult, _a1 error) *MockTasks_GetResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTasks_GetResult_Call) RunAndReturn(run func(context.Context, string) (*TaskWorkflowResult, error)) *MockTasks_GetResult_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function with given fields: ctx, request
func (_m *MockTasks) Enqueue(ctx context.Context, request WorkflowRequest) (*TaskResult, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 *TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, WorkflowRequest) (*TaskResult, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, WorkflowRequest) *TaskResult); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, WorkflowRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTasks_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockTasks_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - request WorkflowRequest
func (_e *MockTasks_Expecter) Enqueue(ctx interface{}, request interface{}) *MockTasks_Enqueue_Call {
	return &MockTasks_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, request)}
}

func (_c *MockTasks_Enqueue_Call) Run(run func(ctx context.Context, request WorkflowRequest)) *MockTasks_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(WorkflowRequest))
	})
	return _c
}

func (_c *MockTasks_Enqueue_Call) Return(_a0 *TaskResult, _a1 error) *MockTasks_Enqueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTasks_Enqueue_Call) RunAndReturn(run func(context.Context, WorkflowRequest) (*TaskResult, error)) *MockTasks_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTasks creates a new instance of MockTasks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTasks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTasks {
	mock := &MockTasks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
