openapi: 3.0.1
info:
  contact: {}
  title: Feed API
  version: "1.0"
servers:
- url: //localhost:8080/v1
paths:
  /articles/{id}:
    get:
      description: view article
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server.ArticleResponse'
          description: OK
        "500":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: Internal Server Error
      summary: view article
  /feeds:
    get:
      description: list feeds
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server.FeedsResponse'
          description: OK
        "500":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: Internal Server Error
      summary: list feeds
    post:
      description: create feed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/server.CreateFeedRequest'
        description: feed data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server.FeedCreateResponse'
          description: OK
        "500":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: Internal Server Error
      summary: create feed
      x-codegen-request-body-name: request
  /feeds/{id}:
    get:
      description: view feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server.FeedResponse'
          description: OK
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server.ErrorResponse'
          description: Internal Server Error
      summary: view feed
    post:
      description: update feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/server.UpdateFeedRequest'
        description: feed data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server.FeedUpdateResponse'
          description: OK
        "500":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: Internal Server Error
      summary: update feed
      x-codegen-request-body-name: request
  /feeds/{id}/articles:
    get:
      description: list articles for a feed
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/server.FeedArticlesResponse'
          description: OK
        "500":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: Internal Server Error
      summary: list articles for a feed
components:
  schemas:
    gorm.DeletedAt:
      example:
        valid: true
        time: time
      properties:
        time:
          type: string
        valid:
          description: Valid is true if Time is not NULL
          type: boolean
      type: object
    models.Article:
      example:
        preview: Article preview text. May contain HTML.
        authorEmail: example@example.com
        title: Example Article
        content: Article content text. May contain HTML.
        url: https://example.com/
        createdAt: 2021-01-01T00:00:00Z
        feed:
          createdAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          name: Example
          id: 1
          url: https://example.com/
          updatedAt: 2021-01-01T00:00:00Z
        deletedAt:
          valid: true
          time: time
        authorName: Eric Butera
        imageUrl: https://example.com/image.jpg
        guid: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
        id: 1
        updatedAt: 2021-01-01T00:00:00Z
      properties:
        authorEmail:
          example: example@example.com
          type: string
        authorName:
          example: Eric Butera
          type: string
        content:
          example: Article content text. May contain HTML.
          type: string
        createdAt:
          example: 2021-01-01T00:00:00Z
          type: string
        deletedAt:
          $ref: '#/components/schemas/gorm.DeletedAt'
        feed:
          $ref: '#/components/schemas/models.Feed'
        guid:
          example: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
          type: string
        id:
          example: 1
          type: integer
        imageUrl:
          example: https://example.com/image.jpg
          type: string
        preview:
          example: Article preview text. May contain HTML.
          type: string
        title:
          example: Example Article
          type: string
        updatedAt:
          example: 2021-01-01T00:00:00Z
          type: string
        url:
          example: https://example.com/
          type: string
      required:
      - id
      - url
      type: object
    models.Feed:
      example:
        createdAt: 2021-01-01T00:00:00Z
        deletedAt:
          valid: true
          time: time
        name: Example
        id: 1
        url: https://example.com/
        updatedAt: 2021-01-01T00:00:00Z
      properties:
        createdAt:
          example: 2021-01-01T00:00:00Z
          type: string
        deletedAt:
          $ref: '#/components/schemas/gorm.DeletedAt'
        id:
          example: 1
          type: integer
        name:
          example: Example
          type: string
        updatedAt:
          example: 2021-01-01T00:00:00Z
          type: string
        url:
          example: https://example.com/
          type: string
      required:
      - id
      - url
      type: object
    server.ArticleResponse:
      example:
        article:
          preview: Article preview text. May contain HTML.
          authorEmail: example@example.com
          title: Example Article
          content: Article content text. May contain HTML.
          url: https://example.com/
          createdAt: 2021-01-01T00:00:00Z
          feed:
            createdAt: 2021-01-01T00:00:00Z
            deletedAt:
              valid: true
              time: time
            name: Example
            id: 1
            url: https://example.com/
            updatedAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          authorName: Eric Butera
          imageUrl: https://example.com/image.jpg
          guid: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
          id: 1
          updatedAt: 2021-01-01T00:00:00Z
      properties:
        article:
          $ref: '#/components/schemas/models.Article'
      type: object
    server.CreateFeed:
      properties:
        url:
          example: https://example.com/feed.xml
          type: string
      required:
      - url
      type: object
    server.CreateFeedRequest:
      properties:
        feed:
          $ref: '#/components/schemas/server.CreateFeed'
      type: object
    server.ErrorResponse:
      example:
        error: unable to fetch feeds
      properties:
        error:
          example: unable to fetch feeds
          type: string
      type: object
    server.FeedArticlesResponse:
      example:
        articles:
        - preview: Article preview text. May contain HTML.
          authorEmail: example@example.com
          title: Example Article
          content: Article content text. May contain HTML.
          url: https://example.com/
          createdAt: 2021-01-01T00:00:00Z
          feed:
            createdAt: 2021-01-01T00:00:00Z
            deletedAt:
              valid: true
              time: time
            name: Example
            id: 1
            url: https://example.com/
            updatedAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          authorName: Eric Butera
          imageUrl: https://example.com/image.jpg
          guid: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
          id: 1
          updatedAt: 2021-01-01T00:00:00Z
        - preview: Article preview text. May contain HTML.
          authorEmail: example@example.com
          title: Example Article
          content: Article content text. May contain HTML.
          url: https://example.com/
          createdAt: 2021-01-01T00:00:00Z
          feed:
            createdAt: 2021-01-01T00:00:00Z
            deletedAt:
              valid: true
              time: time
            name: Example
            id: 1
            url: https://example.com/
            updatedAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          authorName: Eric Butera
          imageUrl: https://example.com/image.jpg
          guid: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
          id: 1
          updatedAt: 2021-01-01T00:00:00Z
      properties:
        articles:
          items:
            $ref: '#/components/schemas/models.Article'
          type: array
      type: object
    server.FeedCreateResponse:
      example:
        feed: "{}"
      properties:
        feed:
          allOf:
          - $ref: '#/components/schemas/models.Feed'
          description: "TODO: limit fields"
          type: object
      type: object
    server.FeedResponse:
      example:
        feed:
          createdAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          name: Example
          id: 1
          url: https://example.com/
          updatedAt: 2021-01-01T00:00:00Z
      properties:
        feed:
          $ref: '#/components/schemas/models.Feed'
      type: object
    server.FeedUpdateResponse:
      example:
        feed:
          createdAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          name: Example
          id: 1
          url: https://example.com/
          updatedAt: 2021-01-01T00:00:00Z
      properties:
        feed:
          $ref: '#/components/schemas/models.Feed'
      type: object
    server.FeedsResponse:
      example:
        feeds:
        - createdAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          name: Example
          id: 1
          url: https://example.com/
          updatedAt: 2021-01-01T00:00:00Z
        - createdAt: 2021-01-01T00:00:00Z
          deletedAt:
            valid: true
            time: time
          name: Example
          id: 1
          url: https://example.com/
          updatedAt: 2021-01-01T00:00:00Z
      properties:
        feeds:
          items:
            $ref: '#/components/schemas/models.Feed'
          type: array
      type: object
    server.UpdateFeed:
      properties:
        url:
          example: https://example.com/feed.xml
          type: string
      required:
      - url
      type: object
    server.UpdateFeedRequest:
      properties:
        feed:
          $ref: '#/components/schemas/server.UpdateFeed'
      type: object
x-original-swagger-version: "2.0"
