/*
Feed API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServerUpdateFeed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerUpdateFeed{}

// ServerUpdateFeed struct for ServerUpdateFeed
type ServerUpdateFeed struct {
	Url string `json:"url"`
}

type _ServerUpdateFeed ServerUpdateFeed

// NewServerUpdateFeed instantiates a new ServerUpdateFeed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerUpdateFeed(url string) *ServerUpdateFeed {
	this := ServerUpdateFeed{}
	this.Url = url
	return &this
}

// NewServerUpdateFeedWithDefaults instantiates a new ServerUpdateFeed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerUpdateFeedWithDefaults() *ServerUpdateFeed {
	this := ServerUpdateFeed{}
	return &this
}

// GetUrl returns the Url field value
func (o *ServerUpdateFeed) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ServerUpdateFeed) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ServerUpdateFeed) SetUrl(v string) {
	o.Url = v
}

func (o ServerUpdateFeed) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerUpdateFeed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ServerUpdateFeed) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServerUpdateFeed := _ServerUpdateFeed{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServerUpdateFeed)

	if err != nil {
		return err
	}

	*o = ServerUpdateFeed(varServerUpdateFeed)

	return err
}

type NullableServerUpdateFeed struct {
	value *ServerUpdateFeed
	isSet bool
}

func (v NullableServerUpdateFeed) Get() *ServerUpdateFeed {
	return v.value
}

func (v *NullableServerUpdateFeed) Set(val *ServerUpdateFeed) {
	v.value = val
	v.isSet = true
}

func (v NullableServerUpdateFeed) IsSet() bool {
	return v.isSet
}

func (v *NullableServerUpdateFeed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerUpdateFeed(val *ServerUpdateFeed) *NullableServerUpdateFeed {
	return &NullableServerUpdateFeed{value: val, isSet: true}
}

func (v NullableServerUpdateFeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerUpdateFeed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


