/*
Feed API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ServerUpdateFeedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerUpdateFeedRequest{}

// ServerUpdateFeedRequest struct for ServerUpdateFeedRequest
type ServerUpdateFeedRequest struct {
	Feed *ServerUpdateFeed `json:"feed,omitempty"`
}

// NewServerUpdateFeedRequest instantiates a new ServerUpdateFeedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerUpdateFeedRequest() *ServerUpdateFeedRequest {
	this := ServerUpdateFeedRequest{}
	return &this
}

// NewServerUpdateFeedRequestWithDefaults instantiates a new ServerUpdateFeedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerUpdateFeedRequestWithDefaults() *ServerUpdateFeedRequest {
	this := ServerUpdateFeedRequest{}
	return &this
}

// GetFeed returns the Feed field value if set, zero value otherwise.
func (o *ServerUpdateFeedRequest) GetFeed() ServerUpdateFeed {
	if o == nil || IsNil(o.Feed) {
		var ret ServerUpdateFeed
		return ret
	}
	return *o.Feed
}

// GetFeedOk returns a tuple with the Feed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerUpdateFeedRequest) GetFeedOk() (*ServerUpdateFeed, bool) {
	if o == nil || IsNil(o.Feed) {
		return nil, false
	}
	return o.Feed, true
}

// HasFeed returns a boolean if a field has been set.
func (o *ServerUpdateFeedRequest) HasFeed() bool {
	if o != nil && !IsNil(o.Feed) {
		return true
	}

	return false
}

// SetFeed gets a reference to the given ServerUpdateFeed and assigns it to the Feed field.
func (o *ServerUpdateFeedRequest) SetFeed(v ServerUpdateFeed) {
	o.Feed = &v
}

func (o ServerUpdateFeedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerUpdateFeedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Feed) {
		toSerialize["feed"] = o.Feed
	}
	return toSerialize, nil
}

type NullableServerUpdateFeedRequest struct {
	value *ServerUpdateFeedRequest
	isSet bool
}

func (v NullableServerUpdateFeedRequest) Get() *ServerUpdateFeedRequest {
	return v.value
}

func (v *NullableServerUpdateFeedRequest) Set(val *ServerUpdateFeedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServerUpdateFeedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServerUpdateFeedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerUpdateFeedRequest(val *ServerUpdateFeedRequest) *NullableServerUpdateFeedRequest {
	return &NullableServerUpdateFeedRequest{value: val, isSet: true}
}

func (v NullableServerUpdateFeedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerUpdateFeedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


