/*
Feed API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ServerCreateFeedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerCreateFeedRequest{}

// ServerCreateFeedRequest struct for ServerCreateFeedRequest
type ServerCreateFeedRequest struct {
	Feed *ServerCreateFeed `json:"feed,omitempty"`
}

// NewServerCreateFeedRequest instantiates a new ServerCreateFeedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerCreateFeedRequest() *ServerCreateFeedRequest {
	this := ServerCreateFeedRequest{}
	return &this
}

// NewServerCreateFeedRequestWithDefaults instantiates a new ServerCreateFeedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerCreateFeedRequestWithDefaults() *ServerCreateFeedRequest {
	this := ServerCreateFeedRequest{}
	return &this
}

// GetFeed returns the Feed field value if set, zero value otherwise.
func (o *ServerCreateFeedRequest) GetFeed() ServerCreateFeed {
	if o == nil || IsNil(o.Feed) {
		var ret ServerCreateFeed
		return ret
	}
	return *o.Feed
}

// GetFeedOk returns a tuple with the Feed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerCreateFeedRequest) GetFeedOk() (*ServerCreateFeed, bool) {
	if o == nil || IsNil(o.Feed) {
		return nil, false
	}
	return o.Feed, true
}

// HasFeed returns a boolean if a field has been set.
func (o *ServerCreateFeedRequest) HasFeed() bool {
	if o != nil && !IsNil(o.Feed) {
		return true
	}

	return false
}

// SetFeed gets a reference to the given ServerCreateFeed and assigns it to the Feed field.
func (o *ServerCreateFeedRequest) SetFeed(v ServerCreateFeed) {
	o.Feed = &v
}

func (o ServerCreateFeedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerCreateFeedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Feed) {
		toSerialize["feed"] = o.Feed
	}
	return toSerialize, nil
}

type NullableServerCreateFeedRequest struct {
	value *ServerCreateFeedRequest
	isSet bool
}

func (v NullableServerCreateFeedRequest) Get() *ServerCreateFeedRequest {
	return v.value
}

func (v *NullableServerCreateFeedRequest) Set(val *ServerCreateFeedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServerCreateFeedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServerCreateFeedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerCreateFeedRequest(val *ServerCreateFeedRequest) *NullableServerCreateFeedRequest {
	return &NullableServerCreateFeedRequest{value: val, isSet: true}
}

func (v NullableServerCreateFeedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerCreateFeedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


