{
 "title": "api - database",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "combined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"go_sql.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections_closed_max_lifetime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_sql_connections_closed_max_lifetime_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections_closed_max_idle_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_sql_connections_closed_max_idle_time_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections_wait_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_sql_connections_wait_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections_closed_max_idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "go_sql_connections_closed_max_idle_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_sql_connections_closed_max_idle_time_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections_idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "go_sql_connections_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "connections_wait_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "go_sql_connections_wait_duration_nanoseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connections_max_open",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "go_sql_connections_max_open", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "connections_in_use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "go_sql_connections_in_use", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go.sql.connections_open",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "go_sql_connections_open", "legendFormat": "__auto" }
   ]
  }
 ]
}