name: All Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buf-lint:
    uses: ./.github/workflows/buf-lint.yaml
    secrets: inherit

  # note: golang-checks have been moved to go-coverage and golangci-lint.yaml (much nicer)
  # i still prefer to have the ability to run these fast & locally. it's possible to run
  # these locally with act, but it is a bit slow. this should also be reflected in
  # pre-commit. it's very jarring when something behaves differently locally vs in CI.

  ts-checks:
    uses: ./.github/workflows/ts-checks.yaml
    secrets: inherit

  tilt-ci:
    needs: [ts-checks, buf-lint]
    uses: ./.github/workflows/tilt-ci.yaml
    secrets: inherit
