name: All Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# TODO: cache checkout (if possible)
# TODO: cache go modules
jobs:
  # TODO: break into lint-go, lint-typescript
  lint:
    uses: ./.github/workflows/lint.yaml
    secrets: inherit

  # TODO: break into unit-test-go, unit-test-typescript
  unit-test:
    uses: ./.github/workflows/unit-test.yaml
    secrets: inherit

  tilt-ci:
    needs: [lint, unit-test]
    uses: ./.github/workflows/tilt-ci.yaml
    secrets: inherit

  # TODO: PR environment
  # TODO: build images
  # TODO: push images
  # TODO: seperate deploy workflow