name: All Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# TODO: cache checkout (if possible)
# TODO: cache go modules
jobs:
  golang-lint:
    uses: ./.github/workflows/golang-lint.yaml
    secrets: inherit

  golang-test:
    uses: ./.github/workflows/golang-test.yaml
    secrets: inherit

  ts-lint:
    uses: ./.github/workflows/ts-lint.yaml
    secrets: inherit

  # TODO: https://nextjs.org/docs/app/building-your-application/testing/jest
  # ts-test:
  #   uses: ./.github/workflows/ts-test.yaml
  #   secrets: inherit

  tilt-ci:
    needs: [golang-lint, golang-test, ts-lint] # TODO: ts-test
    uses: ./.github/workflows/tilt-ci.yaml
    secrets: inherit
