name: All Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golang-checks:
    uses: ./.github/workflows/golang-checks.yaml
    secrets: inherit

  ts-checks:
    uses: ./.github/workflows/ts-checks.yaml
    secrets: inherit

  # TODO: https://nextjs.org/docs/app/building-your-application/testing/jest
  # ts-test:
  #   uses: ./.github/workflows/ts-test.yaml
  #   secrets: inherit

  tilt-ci:
    needs: [golang-checks, ts-checks]
    uses: ./.github/workflows/tilt-ci.yaml
    secrets: inherit
