name: All Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buf-lint:
    uses: ./.github/workflows/buf-lint.yaml
    secrets: inherit

  golang-checks:
    uses: ./.github/workflows/golang-checks.yaml
    secrets: inherit

  ts-checks:
    uses: ./.github/workflows/ts-checks.yaml
    secrets: inherit

  tilt-ci:
    needs: [golang-checks, ts-checks]
    uses: ./.github/workflows/tilt-ci.yaml
    secrets: inherit
