# Golang code coverage. This will add a comment to the PR with the code coverage report.
# https://github.com/fgrosse/go-coverage-report/tree/8c1d1a09864211d258937b1b1a5b849f7e4f2682
#
# Note: On first run this will throw an error saying coverage artifact doesn't exist.
name: golang-coverage
on:
  workflow_call: # reusable
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22

      - name: Test
        run: go test -cover -coverprofile=coverage.txt ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.txt

  coverage-report:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      GITHUB_BASELINE_WORKFLOW: go-coverage.yaml
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - uses: fgrosse/go-coverage-report@v1.1.1
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.txt"
