name: golang-checks
on:
  workflow_call: # reusable

permissions:
  contents: read

jobs:
  golang-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: extractions/setup-just@v2
      - run: just go-checks
