name: golangci-lint
on:
  workflow_call: # reusable

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golang-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
      - run: "go vet ./..."
