name: golang test

on:
  workflow_call: # reusable

jobs:
  golang-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: make test
