# Golang linters. I still want to enable more linters. It would be even nicer to only lint on
# changed files.
name: golangci-lint
on:
  workflow_call: # reusable

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run go-lint-ci
