# tilt-ci is a platform agnostic continuous integration tool. this gives the
# flexibility to move to different CI platforms (ie GitHub Actions, GitLab CI,
# Jenkins, etc) with a guaranteed consistent experience.
name: tilt-ci

on:
  workflow_call: # reusable

jobs:
  tilt-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: mise run ci
