name: Run Tilt CI

on:
  workflow_call: # reusable

jobs:
  tilt-ci:
    runs-on: ubuntu-latest

    # TODO: create custom image that contains all build dependencies
    # container:
    #   image: golang:1.23.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2" # TODO: use variable

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install Tilt
        env:
          VERSION: 0.33.20
          ARCH: amd64
        run: |
          curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v0.33.20/tilt.0.33.20.linux.x86_64.tar.gz | tar -xzv -C /usr/local/bin

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Run Tilt CI
        run: |
          make ci
