# tilt-ci is a platform agnostic continuous integration tool. this gives the
# flexibility to move to different CI platforms (ie GitHub Actions, GitLab CI,
# Jenkins, etc) with a guaranteed consistent experience.
name: tilt-ci

on:
  workflow_call: # reusable

jobs:
  tilt-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            kubectl 1.31.2
            helm 3.16.3
            ctlptl 0.8.36
            kind 0.25.0
            tilt 0.33.21
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: docker/setup-buildx-action@v2
      - uses: extractions/setup-just@v2
      - run: just ci
