# tilt-ci is a platform agnostic continuous integration tool. this gives the
# flexibility to move to different CI platforms (ie GitHub Actions, GitLab CI,
# Jenkins, etc) with a guaranteed consistent experience.
name: tilt-ci

on:
  workflow_call: # reusable

jobs:
  tilt-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: install tilt
        run: |
          curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
      - name: install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
      - name: run tilt ci
        run: |
          make ci
