# tilt-ci is a platform agnostic continuous integration tool. this gives the
# flexibility to move to different CI platforms (ie GitHub Actions, GitLab CI,
# Jenkins, etc) with a guaranteed consistent experience.
name: tilt-ci

on:
  workflow_call: # reusable

jobs:
  tilt-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            helm 3.16.3
            tilt 0.33.21
            kubectl 1.31.2
            ctlptl 0.8.36
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: docker/setup-buildx-action@v2
      - uses: extractions/setup-just@v2
      - run: just ci
