# Typescript checks; used in the UI project.
name: typescript-checks
on:
  workflow_call: # reusable

jobs:
  ts-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run ts-checks
