name: typescript-unit-test
on:
  workflow_call: # reusable

jobs:
  ts-unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run test
