name: PR - Tests

on:
  workflow_call: # reusable

jobs:
  tilt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2" # TODO: use variable

      - name: Run Tests
        run: make test
